# Generated by Django 5.2.14 on 2026-06-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_quote_subtotal_quote_tax_amount_quote_total_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
