# Generated by Django 6.0.1 on 2026-05-14 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0015_marketing_attribution'),
        ('tasks', '0022_alter_task_campaign'),
        ('deals', '0017_alter_deal_campaign'),
        ('leads', '0013_alter_lead_campaign'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Campaign',
        ),
    ]
